### ISSUE TITLE
Update link in Blog

### ISSUE THREAD

**Issue by tzugen** [canadaduane/my-pop-os-conf#1]
Thanks for the great writeup, it was just what i was looking for.
The link to your keyd config in the blog post to the repo is broken:
https://medium.com/@canadaduane/key-remapping-in-linux-2021-edition-47320999d2aa

Under the screenshot of keyd config is this link:
https://github.com/canadaduane/my-pop-os-conf/blob/main/keyboard/keyd/default.cfg

I guess it should link to:
https://github.com/canadaduane/my-pop-os-conf/tree/main/keyboard/keyd

**Comment by canadaduane** [comment]
Thank you! Fixed.
