### ISSUE TITLE
Add window left + right shortcut

### ISSUE THREAD

**Issue by anthonyattard** [canadaduane/my-pop-os-conf#2]
Thanks for this repo, it's been very useful. Anyway my question is how to add shortcut `cmd+opt+left` to put window left side of screen and `cmd+opt+right` to put window right side of screen. This is the commands for xte, that works to remap my mouse buttons. Need to do the same for `keyd/default.conf`

```sh
# Window Left
"xte 'keydown Control_L' 'keydown Super_L' 'key Left' 'keyup Super_L' 'keyup Control_L'"
   b:9

# Window Right
"xte 'keydown Control_L' 'keydown Super_L' 'key Right' 'keyup Super_L' 'keyup Control_L'"
   b:8
```

Thanks!

**Comment by anthonyattard** [comment]
Some more background am trying to replicate the behavior of mac app "Rectangle" on Pop. https://github.com/rxhanson/Rectangle

**Comment by canadaduane** [comment]
This is a cool idea! I'm sorry I don't have a solution at the moment. I'm curious if you found one since posting though?

**Comment by anthonyattard** [comment]
I have not, will let you know if I find a way! Thanks for the reply and sharing your awesome config!

**Comment by canadaduane** [comment]
In the Pop!_OS Settings, you can go to "Keyboard" -> "Keyboard Shortcuts" -> "Windows" and edit the "View split on left" and "View split on right" keys to make the current window snap to the left-hand or right-hand side of the screen:

![image](https://github.com/canadaduane/my-pop-os-conf/assets/129/b162c31e-baac-4603-97ab-ecce85eac56d)

Does this work for you?

**Comment by anthonyattard** [comment]
Awesome your shortcut was just off by one key but gave me a good hint on how to get it to work! The shortcut I was missing was `control+alt+left` & `control+alt+right`. What made it confusing was that i'm actually hitting different keys on the keyboard due to the global key remapper. Thanks for the help! Here is the setup:

![2023-07-27_19-36](https://github.com/canadaduane/my-pop-os-conf/assets/8838135/778a6fe1-7278-4371-b41e-dbf1cceca276)
